version: '2'
services:
 nginx:
  build: ./nginx
  image: nginx
  ports: 
   - "80:80"
  volumes:
   - ./magento:/usr/share/nginx/html
 # network_mode: "host" 
#  links:
#   - php

 mysql:
  build: ./mysql
  image: mysql
 # ports:
 #  - "3306"
  environment:
   - MYSQL_ROOT_PASSWORD=123qwe
   - MYSQL_DATABASE=magento
   - MYSQL_USER=andrey
   - MYSQL_PASSWORD=123qwe
  #net: "host"
  #network_mode: "host"

 php:
  build: ./php
  image: php
  #ports:
  # - "9000"
  volumes:
   - ./magento:/usr/share/nginx/html
  #net: "host"
 # links:
 #  - mysql
#  network_mode: "host"
  extra_hosts:
   - "magento.dev:nginx"
