version: '2'
services:

 mysql:
  build: ./mysql
  image: mysql
  ports:
   - "3306:3306"
  environment:
   - MYSQL_ROOT_PASSWORD=123qwe
   - MYSQL_DATABASE=magento
   - MYSQL_USER=andrey
   - MYSQL_PASSWORD=123qwe
  network_mode: "host"

 php:
  build: ./php
  image: php
  ports:
   - "9000:9000"
  volumes:
   - ./magento:/usr/share/nginx/html
  network_mode: "host"

 nginx:
  build: ./nginx
  image: nginx
  ports:
   - "8080:80"
  volumes:
   - ./magento:/usr/share/nginx/html
  network_mode: "host"





#networks:
#  magento_net:
#    driver: bridge
#    ipam:
#      config:
#       - subnet: 192.168.0.0/16
#         ip_range: 192.168.2.0/24
#         gateway: 192.168.2.254
#         aux_addresses:
#          mysql: 192.168.2.5
#          nginx: 192.168.2.6
#          php: 192.168.2.7

